[package]
name = "pixelutil-image"
version = "0.1.0"
edition = "2021"
description = "Pixel utilities for image-rs crate"
authors = ["Rostyslav Bohomaz <rostyslav.db@gmail.com>"]
license = "MIT"

[dependencies]
image = { version = "0.25.1", default-features = false }
